-- MySQL Script generated by MySQL Workbench
-- Mon Jul 23 20:36:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema node_tut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema node_tut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `node_tut` DEFAULT CHARACTER SET utf8 ;
USE `node_tut` ;

-- -----------------------------------------------------
-- Table `node_tut`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_tut`.`users` (
  `userID` INT(11) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `node_tut`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `node_tut`.`vehicles` (
  `vehicleID` INT(11) NOT NULL,
  `vehicleName` VARCHAR(45) NOT NULL,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`vehicleID`, `userID`),
  UNIQUE INDEX `vehicleID_UNIQUE` (`vehicleID` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `node_tut`.`users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
